# Site settings
title: Viktor Jacynycz
description: DevOps Engineer at Stratio BD
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jacynycz.github.io/" # the base hostname & protocol for your site e.g. https://willianjusten.com.br

# User settings
username: Viktor Jacynycz
user_title: DevOps Engineer at StratioBD
email: viktor@jacynycz.es
twitter_username: jacynycz
github_username:  Jacynycz

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman